# Form implementation generated from reading ui file 'app/gui/admin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 601, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setAccessibleName("")
        self.widget.setObjectName("widget")
        self.users = QtWidgets.QTableView(parent=self.widget)
        self.users.setGeometry(QtCore.QRect(10, 10, 581, 251))
        self.users.setObjectName("users")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(500, 280, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.widget, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.history = QtWidgets.QTableView(parent=self.widget1)
        self.history.setGeometry(QtCore.QRect(10, 10, 581, 251))
        self.history.setObjectName("history")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 280, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.widget1, "")
        self.widget2 = QtWidgets.QWidget()
        self.widget2.setObjectName("widget2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget2)
        self.lineEdit.setGeometry(QtCore.QRect(50, 50, 251, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget2)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 120, 251, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget2)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 190, 251, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(parent=self.widget2)
        self.label.setGeometry(QtCore.QRect(50, 20, 461, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget2)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 461, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget2)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 461, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget2)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 110, 131, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.widget2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.widget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>all clients</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "All users"))
        self.pushButton_3.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget1), _translate("MainWindow", "Users History"))
        self.label.setText(_translate("MainWindow", "database path"))
        self.label_2.setText(_translate("MainWindow", "ip address"))
        self.label_3.setText(_translate("MainWindow", "port"))
        self.pushButton_2.setText(_translate("MainWindow", "Start server"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget2), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
